---

port: 4000
host: 0.0.0.0
safe: false
baseurl: http://openjordan.net

### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title:       "OpenJordan"
keywords:    "jordan, open jordan, open source, jordan open source association"
description: "A Made-in-Jordan conversation about thinking, doing and beng OPEN: The spirit of openess is out there; from open source software and hardware to the open internet, from open content to open data, we can make this country more open, join us and let's start the mission: #OpenJordan"
source_link: "https://github.com/aqabawe/open-jordan"
favicon:     #put a path like: "img/favicon.ico"
touch_icon:  #put a path like: "img/apple-touch-icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#2e3436'
  white:     '#FFFFFF'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  josa:      '#89D216'

